export const USER_REGISTER = "USER_REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const USER_LOGIN = "USER_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILE_SUCCESS = "GET_PROFILE_SUCCESS";
export const GET_PROFILE_FAIL = "GET_PROFILE_FAIL";

export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_FAIL = "GET_PRODUCT_FAIL";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";

export const EDIT_PRODUCT = "EDIT_PRODUCT";
export const EDIT_PRODUCT_SUCCESS = "EDIT_PRODUCT_SUCCESS";
export const EDIT_PRODUCT_FAIL = "EDIT_PRODUCT_FAIL";

export const ADD_PRODUCT = "ADD_PRODUCT";
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS";
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL";

export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const GET_PRODUCT_BY_SUCCESS = "GET_PRODUCT_BY_SUCCESS";
export const GET_PRODUCT_BY_FAIL = "GET_PRODUCT_BY_FAIL";

export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_PRODUCT_SECCESS = "DELETE_PRODUCT_SECCESS";
export const DELETE_PRODUCT_FAIL = "DELETE_PRODUCT_FAIL";



export const GET_CARD = "GET_CARD";
export const ADD_TO_CARD = "ADD_TO_CARD";
export const DELETE_FROM_CARD = "DELETE_FROM_CARD";
export const UPDATE_CARD = "UPDATE_CARD";

export const QUANT_INCRIMENT = "QUANT_INCRIMENT";
export const QUANT_DECRIMENT = "QUANT_DECRIMENT";

export const PALCE_ORDER = "PALCE_ORDER";
export const PALCE_ORDER_SUCCESS = "PALCE_ORDER_SUCCESS";
export const PALCE_ORDER_FAIL = "PALCE_ORDER_FAIL";


export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_FAIL = "GET_ORDER_FAIL";

export const CONFIRM_ORDER = "CONFIRM_ORDER";
export const CONFIRM_ORDER_SUCCESS = "CONFIRM_ORDER_SUCCESS";
export const CONFIRM_ORDER_FAIL = "CONFIRM_ORDER_FAIL";

export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_SUCC = "DELETE_ORDER_SUCC";
export const DELETE_ORDER_FAIL = "DELETE_ORDER_FAIL";



export const FILTER_NAME = "FILTER_NAME";


export const ADD_LIVREUR = "ADD_LIVREUR";
export const GET_LIVREUR = "GET_LIVREUR";
export const UPDATE_LIVREUR = "UPDATE_LIVREUR";
export const DELETE_LIVREUR = "DELETE_LIVREUR";

export const ADD_CATEGORY = "ADD_CATEGORY";
export const GET_CATEGORY = "GET_CATEGORY";
export const UPDATE_CATEGORY = "UPDATE_CATEGORY";
export const DELETE_CATEGORY = "DELETE_CATEGORY";